### ISSUE TITLE
ZeroTier-One 1.6.6 now availalable

### ISSUE THREAD

**Issue by roberttco** [hassio-addons/addon-zerotier#107]
# Problem/Motivation

The ZeroTier folks have updated to 1.6.6 to address a vulnerability - [https://announce.zerotier.com/en/recommended-zerotier--update](url)

## Expected behavior

The 1.6.6 client is installed

## Actual behavior

The 1.6.2 client is installed

## Steps to reproduce

Install Zero-Tier-One form the addon store

## Proposed changes

Update to ZeroTier One 1.6.6

**Comment by frenck** [comment]
We already updated yesterday: <https://github.com/hassio-addons/addon-zerotier/releases/tag/v0.11.2>
