### ISSUE TITLE
Cannot have more than one secret networks

### ISSUE THREAD

**Issue by axilleas** [hassio-addons/addon-zerotier#11]
# Problem/Motivation

I tried to use more than one network with the `!secret` option, and it doesn't work.

## Expected behavior

Use as many secret networks as you want.

## Actual behavior

Only one secret network is supported.

## Steps to reproduce

Use the following:

```yaml
networks:
  - '!secret zerotier_net_one'
  - '!secret zerotier_net_two'
```

It errors with:

```
Failed to save addon configuration, not a valid value for dictionary value @ data['options'].
Got {'networks': ['!secret zerotier_mpl', '!secret zerotier_dms'], 'api_auth_token': ''}
```

## Proposed changes

I think it has to do with the secret regex in https://github.com/hassio-addons/addon-zerotier/blob/bb7ca099a294231c3858843b855cc515e23e1bc1/zerotier/config.json#L28.

**Comment by frenck** [comment]
Hi there,

Thanks for opening up an issue, however, this is not a limitation of the add-on, nor is it a thing that can be fixed on an add-on level.

Please report the issue with Home Assistant (the Supervisor project).

Thanks! 👍

**Comment by axilleas** [comment]
@frenck thanks, I submitted one in https://github.com/home-assistant/supervisor/issues/1590. Hope that helps.
