### ISSUE TITLE
Suddenly slow after update

### ISSUE THREAD

**Issue by sanderlv** [hassio-addons/addon-zerotier#111]
# Problem/Motivation
Until previous version (pre-0.11.2) it always was very fast. Now after updating to 0.11.2 I experience delay.

> (Why the issue was filed)

## Expected behavior
Normal loading times

> (What you expected to happen)

## Actual behavior
Lovelace dashboard, supervisor, etc. are very slow loading remotely via zerotier now.

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

LOGGING:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ZeroTier One
 Radically simplify your network with a virtual networking layer that works the same everywhere
-----------------------------------------------------------
 Add-on version: 0.11.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.4  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] zerotier.sh: executing... 
[09:36:59] INFO: ZeroTier node address: xxxxxxxxx
[09:37:01] INFO: Configuring network: xxxxxxxxxxxxxxxx
[cont-init.d] zerotier.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:37:02] INFO: Starting ZeroTier One...
[10:34:45] INFO: Starting ZeroTier One...

```

**Comment by sanderlv** [comment]
This is just "don't look don't know". The issue is with the latest version... argh... I hate this 🥴

**Comment by frenck** [comment]
I cannot reproduce the issue, however, I did put out an update with some major updates to both the underlying base and the new ZeroTier One.

**Comment by sanderlv** [comment]
Hi Frenck, does this also include any improvements/enhancements with regards to Samba addon 9.5.1 like described here:
https://github.com/home-assistant/addons/issues/2073#


I really hope so....

**Comment by frenck** [comment]
This is completely unrelated to the samba add-on?

**Comment by sanderlv** [comment]
You say so. I thought it might be related since the samba addon is having issues only with the zerotier addon...

else, thanks for looking into this.
