### ISSUE TITLE
conflict with sonos

### ISSUE THREAD

**Issue by rddoove** [hassio-addons/addon-zerotier#12]
# Problem/Motivation
when zerotier is started my sonos integration stops working

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Configure Sonos manually in that case or make sure it uses the right interface.

For more information see: <https://www.home-assistant.io/integrations/sonos#advanced-use>

**Comment by rddoove** [comment]
I did that  but it was no good... I added the config like this:

sonos:
  media_player:
    hosts:
      - 192.168.178.157
    interface_addr: 192.168.178.155

but as log as zerotier was running the sonos was not reachable

**Comment by frenck** [comment]
I have Sonos & ZeroTier, and do not experience these issues... Sorry m8, but this sounds like a network problem.
