### ISSUE TITLE
Allow Ethernet Bridging?

### ISSUE THREAD

**Issue by ajdezigns** [hassio-addons/addon-zerotier#13]
# Problem/Motivation

> Id like to access my home network from my laptop so I can access a NAS that I can not install this software onto 

## Expected behavior

> be able to mount the NAS drive remotly

## Actual behavior

> N/A

## Steps to reproduce

> N/A

## Proposed changes

> add the ability for "Allow Ethernet Bridging"

**Comment by frenck** [comment]
This add-on cannot provide that unfortunately.
