### ISSUE TITLE
IP forwarding

### ISSUE THREAD

**Issue by sn-sn** [hassio-addons/addon-zerotier#14]
hello friend!
I have free vps on cloud.google.com. I installed zerotier on my server (on cloud.google), on my android phone and addon on home assistant (on raspberry pi). I configured the network. I can connect to home assistant using my android via zerotier. I checked the ping from my server to the ip address(managed ip on zerotier) assigned to my raspberry with home assistant.
I want IP forwarding From my Public IP(server google cloud) to Managed IP zerotier. Its need for access on my home assistant via my Public IP(server google cloud). What i doing:
1. Im add on Managed Routes Destination (my Public IP server google cloud) Via (managed ip on zerotier my raspberry pi)
2. Configurate net.ipv4.ip_forward = 1 (/etc/sysctl.conf)  on my server google cloud
3. Use on my server google cloud `sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE` and `sudo iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT` and `sudo iptables -A FORWARD -i ztr2qr4pmm -o eth0 -j ACCEPT`
4. On raspberry pi configurate net.ipv4.conf.all.rp_filter=2 (/etc/sysctl.conf)
5. As i know need configurate allowDefault=1. I cant find on addon zerotieron home assistant option "allowDefault". How turn on "allowDefault" ?
Sorry for my english and thanks for your work.

**Comment by frenck** [comment]
The add-on cannot do that, as it runs in an isolated network environment.
