### ISSUE TITLE
Home Assistant does not connect

### ISSUE THREAD

**Issue by Roglogg** [hassio-addons/addon-zerotier#15]
# Problem/Motivation
ZeroTier tells me that I am offline, but the log says that I am online.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ZeroTier One
 Radically simplify your network with a virtual networking layer that works the same everywhere
-----------------------------------------------------------
 Add-on version: 0.7.3
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] zerotier.sh: executing... 
[09:46:44] INFO: ZeroTier node address: ********
[09:46:44] INFO: Configuring network: *******
[cont-init.d] zerotier.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:46:44] INFO: Starting ZeroTier One...

I've already tried installing ZeroTier, but it keeps saying I'm not online.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Roglogg** [comment]
It always worked well for me. Yesterday afternoon was the failure and today it still does not connect.

**Comment by batas** [comment]
I have a similar problem, my hassio can't connect to zerotier. I tried to downgrade the add-on to 0.7.2 but it doesn't work too.

**Comment by Roglogg** [comment]
My problem has not been solved. More than 48 without connection. I have also completely uninstalled and reinstalled.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ZeroTier One
 Radically simplify your network with a virtual networking layer that works the same everywhere
-----------------------------------------------------------
 Add-on version: 0.7.3
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] zerotier.sh: executing... 
[09:46:44] INFO: ZeroTier node address: *******
[09:46:44] INFO: Configuring network: *******
[cont-init.d] zerotier.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:46:44] INFO: Starting ZeroTier One...

**Comment by Roglogg** [comment]
13 days without connection.

**Comment by diamant-x** [comment]
I'm new to this add-on but it is connecting fine for me. Try a clean add-on install in the latest versions:
-  Add-on version: 0.7.3
-  System: HassOS 4.13  (aarch64 / raspberrypi3-64)
-  Home Assistant Core: 0.115.2
-  Home Assistant Supervisor: 245

Additionally for troubleshooting, you can install the _COMMUNITY_ ssh addon, and in the hassio host check with **ifconfig** if there is a zerotier network interface created and with which IP.

**Comment by matthew73210** [comment]
Hey all,

Error still seems prevalent. This is the log I'm getting:

`[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] zerotier.sh: executing... 
[07:54:16] INFO: ZeroTier node address: f40110e1c4
[07:54:16] INFO: Configuring network: 17d709436caa826b
[cont-init.d] zerotier.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:54:16] INFO: Starting ZeroTier One...
ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory`

Tried all steps mentioned above and still nothing.
Any help ?
Cheers

**Comment by frenck** [comment]
⬆️ ZeroTier One v0.7.4

https://github.com/hassio-addons/addon-zerotier/releases/tag/v0.7.4

I've verified its working on several platforms.
