### ISSUE TITLE
Supervisor page doesn't show

### ISSUE THREAD

**Issue by ThePirat91** [hassio-addons/addon-zerotier#16]
# Problem/Motivation

> Supervisor page on a Home Assistant OS instance doesn't show up when connected by ZeroTier address.
If I connect to the instance by using local lan ip, the page works flawlessly

## Expected behavior

> The Supervisor page works in the same way both connected via zerotier and in the local network.

## Actual behavior

> Supervisor page on a Home Assistant OS instance doesn't show up when connected by ZeroTier address.
If I connect to the instance by using local lan ip, the page works flawlessly.
No info on HA logs

![image](https://user-images.githubusercontent.com/17300013/94135048-31445280-fe63-11ea-892b-43fb99b7ed18.png)

## Environment

>    Add-on version: 0.7.3
    System: HassOS 4.13 (armv7l / raspberrypi4-32)
    Home Assistant Core: 0.115.2
    Home Assistant Supervisor: 245

Thanks

**Comment by frenck** [comment]
I am not able to reproduce this issue.

**Comment by andrey80nik** [comment]
in addition to the supervisor page, the file editor page does not work.

**Comment by andrey80nik** [comment]
The bug disappeared with one of the updates, thank you.
