### ISSUE TITLE
automation does not work / hmip / nuki

### ISSUE THREAD

**Issue by kallejoken** [hassio-addons/addon-zerotier#17]
Hello dear community,

I’m new to the home assistant story and I need your help right away.

I have created an automation system that, when I switch on my hmip alarm system, should also lock my nuki front door lock at the same time.

However, the automation does not work as intended.

If I lock the nuki, for example using a lamp, the lock works perfectly.

The nuki lock works perfectly in all, but not with the automation of the arming of the alarm system.

Who maybe has a solution?

![Screenshot_2020-10-03-10-49-27-793_io homeassistant companion android](https://user-images.githubusercontent.com/72359598/95026959-4310cb80-0695-11eb-9bfa-339d949e4bc3.jpg)
![Screenshot_2020-10-03-10-49-33-906_io homeassistant companion android](https://user-images.githubusercontent.com/72359598/95026961-43a96200-0695-11eb-8365-6f47526135d8.jpg)

**Comment by sinclairpaul** [comment]
Please see https://www.home-assistant.io/help/
