### ISSUE TITLE
How to reset or force the ZT node address?

### ISSUE THREAD

**Issue by PieBru** [hassio-addons/addon-zerotier#18]
# Problem/Motivation

> After addon installation or re-installation, my ZT console doesn't show my server node address. I suspect it is a deleted node, so ZT  has somehow blacklisted it.

## Expected behavior

> Reset the randomly generated ZT node address after addon re-installation.

## Actual behavior

> Deleting and reinstalling the addon the node address remains the same.

## Steps to reproduce

> Look at the addon log after re-installing it.

## Proposed changes

> It may be useful also to be able to force the ZT node address in the addon config.

**Comment by frenck** [comment]
the node address is handled by ZT itself and not controlled by the add-on. Therefore, I cannot answer that question nor offer a solution.

**Comment by PieBru** [comment]
If it may be useful to someone, I solved by manually adding a member with the node-id shown on the ZT addon log.
I blindly didn't notice this option on the ZT console.
Thank you,
Piero

![Screenshot from 2020-11-20 19-26-20](https://user-images.githubusercontent.com/6537434/99836809-eeeb7900-2b66-11eb-86ed-42fa82f5e354.png)
