### ISSUE TITLE
ZeroTier not coming up after update 0.8.0

### ISSUE THREAD

**Issue by SamKr** [hassio-addons/addon-zerotier#19]
I'm having multiple remote home assistant instances which aren't coming online after upgrading zerotier to 0.8.0.
On my local instance, the zerotier log keeps showing the following:

```
[09:09:18] INFO: Starting ZeroTier One...
[09:09:19] INFO: Starting ZeroTier One...
[09:09:20] INFO: Starting ZeroTier One...
[09:09:21] INFO: Starting ZeroTier One...
[09:09:22] INFO: Starting ZeroTier One...
[09:09:23] INFO: Starting ZeroTier One...
[09:09:24] INFO: Starting ZeroTier One...
[09:09:25] INFO: Starting ZeroTier One...
[09:09:26] INFO: Starting ZeroTier One...
[09:09:27] INFO: Starting ZeroTier One...
[09:09:28] INFO: Starting ZeroTier One...
[09:09:29] INFO: Starting ZeroTier One...
```

Home Assistant's log shows this:

```
Logger: zeroconf
Source: /usr/local/lib/python3.8/site-packages/zeroconf/__init__.py:400
First occurred: 8:58:35 AM (2 occurrences)
Last logged: 8:58:42 AM

Error sending through socket 50
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2914, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 19] No such device
```

Any idea what's going on? I've updated Home Assistant to the latest version (0.118.3), but it also applies to 0.118.2.

**Comment by frenck** [comment]
The Home Assistant errors might be a side-effect. Add-ons and Home Assistant run separately so that isn't directly related.

Could you provide details on your system?

**Comment by SamKr** [comment]
I can't connect to the remote systems anymore, but my local system:

```
Operating System
Ubuntu 18.04.3 LTS
Docker version
19.03.1

Supervisor
Version
2020.11.0
Channel
stable

System Health

Home Assistant Core Integration

version: 0.118.3
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.15.0-118-generic
arch: x86_64
timezone: Europe/Amsterdam

Home Assistant Cloud

logged_in: true
subscription_expiration: December 15, 2020, 1:00 AM
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: false
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: Ubuntu 18.04.3 LTS
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.1
disk_total: 116.4 GB
disk_used: 40.4 GB
healthy: failed to load: Unhealthy
supported: failed to load: Unsupported
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.3.0), File editor (5.2.0), Log Viewer (0.9.1), RPC Shutdown (2.2), Terminal & SSH (8.9.1), ZeroTier One (0.8.0), Home Assistant Google Drive Backup (0.102.0), Grocy (0.9.2), MariaDB (2.2.1), Bookstack (0.6.3), AppDaemon 4 (0.3.1), phpMyAdmin (0.1.4), AdGuard Home (2.6.1), FTP (3.5.0), DSS VoIP Notifier (3.4.2), InfluxDB (3.7.9), Grafana (5.3.6), Rhasspy Assistant 2.5 (2.5.7.2)

Lovelace

dashboards: 2
mode: storage
views: 8
resources: 5
```

It's a clean server install, used only for hass.

**Comment by insajd** [comment]
Same issue here. Tried uninstalling/installing back again, same behavior - lots of "INFO: Starting ZeroTier One..." messages.

**Comment by paulgbrichardson** [comment]
I've connected using local IP and ran the add-on with trace enabled - 

[services.d] starting services
[services.d] done.
[09:42:38] INFO: Starting ZeroTier One...
[09:42:38] TRACE: bashio::addon.port 9993
[09:42:38] TRACE: bashio::addons self addons.self.network.9993-tcp .network["9993/tcp"] // empty
[09:42:38] TRACE: bashio::cache.exists: addons.self.network.9993-tcp
[09:42:38] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.network.9993-tcp.cache
[09:42:38] TRACE: bashio::var.false: self
[09:42:38] TRACE: bashio::cache.exists: addons.self.info
[09:42:38] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.info.cache
[09:42:38] TRACE: bashio::cache.get: addons.self.info
[09:42:38] TRACE: bashio::cache.exists: addons.self.info
[09:42:38] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.info.cache
[09:42:38] TRACE: bashio::var.has_value: .network["9993/tcp"] // empty
[09:42:38] TRACE: bashio::jq: {"name":"ZeroTier One","slug":"xxxxxx","hostname":"xxxxxx","dns":["xxxxxxxx"],"description":"Radically simplify your network with a virtual networking layer that works the same everywhere","long_description":"# Home Assistant Community Add-on: ZeroTier One

[![Release][release-shield]][release] ![Project Stage][project-stage-shield] ![Project Maintenance][maintenance-shield]

[![Discord][discord-shield]][discord] [![Community Forum][forum-shield]][forum]

[![Sponsor Frenck via GitHub Sponsors][github-sponsors-shield]][github-sponsors]

[![Support Frenck on Patreon][patreon-shield]][patreon]

Radically simplify your network with a virtual networking layer that works
the same everywhere.

## About

ZeroTier delivers the capabilities of VPNs, SDN, and SD-WAN with a single
system. Manage all your connected resources across both local and wide area
networks as if the whole world is a single data center.

People use ZeroTier to seamlessly connect laptops, desktops, phones,
embedded devices, cloud resources, and apps any way they want anywhere they go.
It transforms the entire world into a single data center, to which you
can now add your Home Assistant instance using this add-on.

[discord-shield]: https://img.shields.io/discord/478094546522079232.svg
[discord]: https://discord.me/hassioaddons
[forum-shield]: https://img.shields.io/badge/community-forum-brightgreen.svg
[forum]: https://community.home-assistant.io/t/home-assistant-community-add-on-zerotier-one/109091?u=frenck
[github-sponsors-shield]: https://frenck.dev/wp-content/uploads/2019/12/github_sponsor.png
[github-sponsors]: https://github.com/sponsors/frenck
[maintenance-shield]: https://img.shields.io/maintenance/yes/2020.svg
[patreon-shield]: https://frenck.dev/wp-content/uploads/2019/12/patreon.png
[patreon]: https://www.patreon.com/frenck
[project-stage-shield]: https://img.shields.io/badge/project%20stage-experimental-yellow.svg
[release-shield]: https://img.shields.io/badge/version-v0.8.0-blue.svg
[release]: https://github.com/hassio-addons/addon-zerotier/tree/v0.8.0","advanced":false,"stage":"stable","auto_update":false,"repository":"a0d7b954","version":"0.8.0","version_latest":"0.8.0","update_available":false,"protected":true,"rating":3,"boot":"auto","options":{"networks":["xxxxxxxxxxx"],"api_auth_token":"","log_level":"trace"},"schema":[{"name":"networks","multiple":true,"required":true,"type":"string"},{"name":"api_auth_token","required":true,"type":"string"},{"name":"log_level","optional":true,"type":"select","options":["trace","debug","info","notice","warning","error","fatal"]}],"arch":["aarch64","amd64","armhf","armv7","i386"],"machine":[],"homeassistant":null,"url":"https://github.com/hassio-addons/addon-zerotier","state":"started","detached":false,"available":true,"build":false,"network":{"9993/tcp":9993},"network_description":{"9993/tcp":"ZeroTier's primary port"},"host_network":true,"host_pid":false,"host_ipc":false,"host_dbus":false,"privileged":["NET_ADMIN","SYS_ADMIN"],"full_access":false,"apparmor":"default","devices":["/dev/net/tun"],"icon":true,"logo":true,"changelog":true,"documentation":true,"stdin":false,"webui":null,"hassio_api":true,"hassio_role":"default","auth_api":false,"homeassistant_api":false,"gpio":false,"usb":false,"kernel_modules":false,"devicetree":false,"udev":false,"docker_api":false,"video":false,"audio":false,"audio_input":null,"audio_output":null,"startup":"services","services":[],"discovery":[],"ip_address":"172.30.32.1","ingress":false,"ingress_entry":null,"ingress_url":null,"ingress_port":null,"ingress_panel":false,"watchdog":false} .network["9993/tcp"] // empty
[09:42:43] INFO: Starting ZeroTier One...
[09:42:43] TRACE: bashio::addon.port 9993
[09:42:43] TRACE: bashio::addons self addons.self.network.9993-tcp .network["9993/tcp"] // empty
[09:42:43] TRACE: bashio::cache.exists: addons.self.network.9993-tcp
[09:42:43] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.network.9993-tcp.cache
[09:42:43] TRACE: bashio::cache.get: addons.self.network.9993-tcp
[09:42:43] TRACE: bashio::cache.exists: addons.self.network.9993-tcp
[09:42:43] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.network.9993-tcp.cache
[09:42:44] INFO: Starting ZeroTier One...

**Comment by akacruel** [comment]
> I'm having multiple remote home assistant instances which aren't coming online after upgrading zerotier to 0.8.0.
> On my local instance, the zerotier log keeps showing the following:
> 
> ```
> [09:09:18] INFO: Starting ZeroTier One...
> [09:09:19] INFO: Starting ZeroTier One...
> [09:09:20] INFO: Starting ZeroTier One...
> [09:09:21] INFO: Starting ZeroTier One...
> [09:09:22] INFO: Starting ZeroTier One...
> [09:09:23] INFO: Starting ZeroTier One...
> [09:09:24] INFO: Starting ZeroTier One...
> [09:09:25] INFO: Starting ZeroTier One...
> [09:09:26] INFO: Starting ZeroTier One...
> [09:09:27] INFO: Starting ZeroTier One...
> [09:09:28] INFO: Starting ZeroTier One...
> [09:09:29] INFO: Starting ZeroTier One...
> ```
> 
> Home Assistant's log shows this:
> 
> ```
> Logger: zeroconf
> Source: /usr/local/lib/python3.8/site-packages/zeroconf/__init__.py:400
> First occurred: 8:58:35 AM (2 occurrences)
> Last logged: 8:58:42 AM
> 
> Error sending through socket 50
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2914, in send
>     bytes_sent = s.sendto(packet, 0, (real_addr, port))
> OSError: [Errno 19] No such device
> ```
> 
> Any idea what's going on? I've updated Home Assistant to the latest version (0.118.3), but it also applies to 0.118.2.

Same issue after update... Ubuntu Server 20.04.1 (only for hass)

**Comment by nepozs** [comment]
Same issue

```
System Health

Home Assistant Core Integration

version: 0.118.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.77
arch: x86_64
timezone: Europe/Warsaw

Home Assistant Cloud

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 219.4 GB
disk_used: 22.4 GB
healthy: true
supported: true
board: intel-nuc
supervisor_api: ok
version_api: ok
installed_addons: Home Assistant Google Drive Backup (0.102.0), Log Viewer (0.9.1), Check Home Assistant configuration (3.6.0), chrony (1.1.2), Samba share (9.3.0), ZeroTier One (0.8.0), Terminal & SSH (8.9.1), motionEye (0.10.2), AppDaemon 3 (5.0.1), ESPHome (1.15.3), Example (3.5.1), Node-RED (7.2.10), Bitwarden RS (0.6.2), ESPHome (dev) (dev), Glances (0.9.1), Grocy (0.9.2), Folding@home (0.2.0), File editor (5.2.0), Spotify Connect (0.8.2), Portainer (1.3.0)

Lovelace

dashboards: 2
mode: storage
views: 16
resources: 13
```

**Comment by nepozs** [comment]
Same issue

```
System Health

Home Assistant Core Integration

version: 0.118.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.77
arch: x86_64
timezone: Europe/Warsaw

Home Assistant Cloud

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 219.4 GB
disk_used: 22.4 GB
healthy: true
supported: true
board: intel-nuc
supervisor_api: ok
version_api: ok
installed_addons: Home Assistant Google Drive Backup (0.102.0), Log Viewer (0.9.1), Check Home Assistant configuration (3.6.0), chrony (1.1.2), Samba share (9.3.0), ZeroTier One (0.8.0), Terminal & SSH (8.9.1), motionEye (0.10.2), AppDaemon 3 (5.0.1), ESPHome (1.15.3), Example (3.5.1), Node-RED (7.2.10), Bitwarden RS (0.6.2), ESPHome (dev) (dev), Glances (0.9.1), Grocy (0.9.2), Folding@home (0.2.0), File editor (5.2.0), Spotify Connect (0.8.2), Portainer (1.3.0)

Lovelace

dashboards: 2
mode: storage
views: 16
resources: 13
```

```
[12:43:53] INFO: Starting ZeroTier One...
[12:43:54] INFO: Starting ZeroTier One...
[12:43:55] INFO: Starting ZeroTier One...
[12:43:56] INFO: Starting ZeroTier One...
[12:43:57] INFO: Starting ZeroTier One...
[12:43:58] INFO: Starting ZeroTier One...
[12:43:59] INFO: Starting ZeroTier One...
[12:44:00] INFO: Starting ZeroTier One...
[12:44:02] INFO: Starting ZeroTier One...
[12:44:03] INFO: Starting ZeroTier One...
[12:44:04] INFO: Starting ZeroTier One...
[12:44:05] INFO: Starting ZeroTier One...
[12:44:06] INFO: Starting ZeroTier One...
[12:44:07] INFO: Starting ZeroTier One...
[12:44:08] INFO: Starting ZeroTier One...
[12:44:09] INFO: Starting ZeroTier One...
[12:44:10] INFO: Starting ZeroTier One...
[12:44:11] INFO: Starting ZeroTier One...
[12:44:12] INFO: Starting ZeroTier One...
[12:44:13] INFO: Starting ZeroTier One...
[12:44:14] INFO: Starting ZeroTier One...
[12:44:15] INFO: Starting ZeroTier One...
[12:44:16] INFO: Starting ZeroTier One...
```


and after uninstall, fresh install and configure
```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ZeroTier One
 Radically simplify your network with a virtual networking layer that works the same everywhere
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: HassOS 4.17  (amd64 / intel-nuc)
 Home Assistant Core: 0.118.3
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] zerotier.sh: executing... 
[12:47:56] INFO: ZeroTier node address: xxxxxxxxxxxxxxxx
[12:47:56] INFO: Configuring network: xxxxxxxxxxxxxxxxxxxxxxxx
[cont-init.d] zerotier.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:47:56] INFO: Starting ZeroTier One...
[12:48:02] INFO: Starting ZeroTier One...
[12:48:03] INFO: Starting ZeroTier One...
[12:48:04] INFO: Starting ZeroTier One...
[12:48:05] INFO: Starting ZeroTier One...
[12:48:06] INFO: Starting ZeroTier One...
[12:48:07] INFO: Starting ZeroTier One...
[12:48:08] INFO: Starting ZeroTier One...
[12:48:09] INFO: Starting ZeroTier One...
[12:48:10] INFO: Starting ZeroTier One...
[12:48:11] INFO: Starting ZeroTier One...
[12:48:12] INFO: Starting ZeroTier One...

```

**Comment by kreisklasse** [comment]
Some problem on an odroidN2

```
System Health
Home Assistant Core Integration

version: 0.118.2
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.7.19
arch: aarch64
timezone: Europe/Berlin

Home Assistant Cloud

logged_in: true
subscription_expiration: 
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: true
google_enabled: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 28.5 GB
disk_used: 3.7 GB
healthy: true
supported: true
board: odroid-n2
supervisor_api: ok
version_api: ok
installed_addons: AdGuard Home (2.6.1), chrony (1.1.2), ZeroTier One (0.8.0), WireGuard (0.4.0), deCONZ (6.5.0), File editor (5.2.0)

Lovelace

dashboards: 1
mode: storage
views: 3
resources: 0
```

**Comment by gufpewga** [comment]
Same here

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ZeroTier One
 Radically simplify your network with a virtual networking layer that works the same everywhere
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: HassOS 4.17  (amd64 / qemux86-64)
 Home Assistant Core: 0.118.3
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] zerotier.sh: executing... 
[15:14:35] INFO: ZeroTier node address: xxxxxxxxx
[15:14:36] INFO: Configuring network: xxxxxxxxxxxxxx
[cont-init.d] zerotier.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:14:36] INFO: Starting ZeroTier One...
[15:14:37] INFO: Starting ZeroTier One...
[15:14:39] INFO: Starting ZeroTier One...
[15:14:40] INFO: Starting ZeroTier One...
[15:14:41] INFO: Starting ZeroTier One...
[15:14:42] INFO: Starting ZeroTier One...
[15:14:44] INFO: Starting ZeroTier One...
[15:14:45] INFO: Starting ZeroTier One...
[15:14:46] INFO: Starting ZeroTier One...
[15:14:48] INFO: Starting ZeroTier One...

**Comment by frenck** [comment]
> I think you should publish 0.7.4 as i.e 0.8.1 for people, who has enabled autoupdate…

That is not how it works. Please use a snapshot.

**Comment by paulgbrichardson** [comment]
Can confirm rollback to an early snapshot resolves the issue as expected.

**Comment by nepozs** [comment]
> 
> 
> > I think you should publish 0.7.4 as i.e 0.8.1 for people, who has enabled autoupdate…
> 
> That is not how it works. Please use a snapshot.

It is not possible to use snapshot, when remote system is unavailable…

**Comment by frenck** [comment]
> It is not possible to use snapshot, when remote system is unavailable…

I'm sorry, but auto-update on a thing you rely on that heavy sounds a bit weird. Things can go wrong; I'm sorry for that, I do test, but in the end, I'm just human.

**Comment by sipodd** [comment]
I got two installations, one bare metal on a raspberry 4,still works. The other is a vm and the add on crashes like mentioned in this issue. 
Here is my debug log, it's repeating the same message over and over again:
Find my System specification below the log. 

[259635.512633] zerotier-one[1367909]: segfault at 7feff48b9e08 ip 000055b28e374a9d sp 00007feff48b9e10 error 6 in zerotier-one[55b28e29c000+1f0000]
[259635.518032] Code: b6 43 12 83 e0 c7 83 c8 88 88 43 12 e9 20 ff ff ff 0f 1f 40 00 4c 8d 6c 24 10 41 8d 6c 24 e5 48 89 da 41 8d 74 24 25 4c 89 ef <e8> be 93 04 00 83 fd 7f 0f 86 6f 02 00 00 41 8d ac 24 65 ff ff ff
[259635.522746] audit: type=1701 audit(1606237772.203:29375): auid=4294967295 uid=0 gid=0 ses=4294967295 subj==docker-default (enforce) pid=1367894 comm="zerotier-one" exe="/usr/sbin/zerotier-one" sig=11 res=1


System Health

Home Assistant Core Integration

version: 0.118.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.77
arch: x86_64
timezone: Europe/Berlin

Home Assistant Cloud

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 23.9 GB
disk_used: 19.0 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: Home Assistant Google Drive Backup (0.102.0), Samba share (9.3.0), Node-RED (7.2.11), File editor (5.2.0), Check Home Assistant configuration (3.6.0), Mosquitto broker (5.1), Home Panel (1.8.3), AppDaemon 4 (0.3.1), Log Viewer (0.9.1), Portainer (1.3.0), Terminal & SSH (8.9.1), Grafana (5.3.6), Visual Studio Code (2.8.2), InfluxDB (3.7.9), ESPHome (1.15.3), ZeroTier One (0.8.0), Glances (0.9.1), SSH & Web Terminal (7.8.0), ADB - Android Debug Bridge (0.6.3), Dnsmasq (1.3)

**Comment by sipodd** [comment]
Sorry, it was the host log. 
Here is the add on log, level trace, to cycles:

[18:44:06] INFO: Starting ZeroTier One...
[18:44:06] TRACE: bashio::addon.port 9993
[18:44:06] TRACE: bashio::addons self addons.self.network.9993-tcp .network["9993/tcp"] // empty
[18:44:06] TRACE: bashio::cache.exists: addons.self.network.9993-tcp
[18:44:06] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.network.9993-tcp.cache
[18:44:06] TRACE: bashio::cache.get: addons.self.network.9993-tcp
[18:44:06] TRACE: bashio::cache.exists: addons.self.network.9993-tcp
[18:44:06] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.network.9993-tcp.cache
[18:44:07] INFO: Starting ZeroTier One...
[18:44:07] TRACE: bashio::addon.port 9993
[18:44:07] TRACE: bashio::addons self addons.self.network.9993-tcp .network["9993/tcp"] // empty
[18:44:07] TRACE: bashio::cache.exists: addons.self.network.9993-tcp
[18:44:07] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.network.9993-tcp.cache
[18:44:07] TRACE: bashio::cache.get: addons.self.network.9993-tcp
[18:44:07] TRACE: bashio::cache.exists: addons.self.network.9993-tcp
[18:44:07] TRACE: bashio::fs.file_exists: /dev/shm/bashio/addons.self.network.9993-tcp.cache

**Comment by nepozs** [comment]
> 
> 
> > It is not possible to use snapshot, when remote system is unavailable…
> 
> I'm sorry, but auto-update on a thing you rely on that heavy sounds a bit weird. Things can go wrong; I'm sorry for that, I do test, but in the end, I'm just human.

I understand why you can't publish old version as new :D but everyone are humans so mistakes like autoupdate turned on remote system are also possible :P

**Comment by rapejim** [comment]
```
System Health

Home Assistant Core Integration

version: 0.118.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.77
arch: x86_64
timezone: Europe/Madrid

Home Assistant Cloud

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 30.8 GB
disk_used: 8.6 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: SSH & Web Terminal (7.8.0), Portainer (1.3.0), Node-RED (7.2.11), File editor (5.2.0), ZeroTier One (0.8.0), ESPHome (1.15.3), Home Assistant Google Drive Backup (0.102.0), AirCast (2.4.1), Duck DNS (1.12.4), WireGuard (0.4.0), TasmoAdmin (0.13.1), Mosquitto broker (5.1), Log Viewer (0.9.1)

Lovelace

dashboards: 2
mode: storage
views: 9
resources: 3
```

I have the same error on my Proxmox VM with Home Assistant OS.
@frenck on my HA installation, ZeroTier isn't mandatory. I can offer me like a beta tester for example if it's help.

**Comment by frenck** [comment]
I got 2 plans: 1 rollback to ZeroTier 1.4.6 (while maintaining the OS upgrades), and the other is a possible fix while maintaining the upgrade.

I consider the latter the wished-for situation, but currently exploring and testing that one.

**Comment by rapejim** [comment]
> I got 2 plans: 1 rollback to ZeroTier 1.4.6 (while maintaining the OS upgrades), and the other is a possible fix while maintaining the upgrade.
> 
> I consider the latter the wished-for situation, but currently exploring and testing that one.

@frenck If you need me to run any tests on my system, let me know without any problem.

----

As a temporary solution for those who need ZeroTier urgently:
- I have stopped the addon from the HA supervisor.
- I have deleted the image `docker rmi hassioaddons/zerotier-amd64:0.8.0`
- I have downloaded the previous image `docker pull hassioaddons/zerotier-amd64:0.7.4`
- I have added the new tag to the downloaded image `docker tag hassioaddons/zerotier-amd64:0.7.4 hassioaddons/zerotier-amd64:0.8.0`
- I have deleted the previous `docker rmi tag hassioaddons/zerotier-amd64:0.7.4`
- And finally I have started the addon again from the HA supervisor.

This is not a definitive solution, but with this we can wait calmly for the definitive solution.

**Comment by frenck** [comment]
@rapejim Sorry, I've hidden your comment. While I get that that might have worked for you. Really, NOBODY should do that, ever. Please use snapshots instead.

Please be aware, that more people might be looking for a solution, and might try doing that stuff without knowledge end may end up with bigger problems.

**Comment by rapejim** [comment]
> @rapejim Sorry, I've hidden your comment. While I get that that might have worked for you. Really, NOBODY should do that, ever. Please use snapshots instead.
> 
> Please be aware, that more people might be looking for a solution, and might try doing that stuff without the knowledge and may end up with bigger problems.

Ok, no problemhor hiding it.

Yes, a snapshot is a better solution, but in my case the last snapshot is from a long time ago 😅 (1 per week) and I have made many changes in this week (yes, it's my fault).
For this reason I thought to use your previous image (0.7.4) as if it was the last one.

When the next image 0.8.1 (or another higher number) comes out my supervisor will suggest me to update the addon (like from 0.7.4 to 0.8.0).
I think it has no major impact, it's as if I didn't update.

**Comment by nepozs** [comment]
@rapejim 
It is possible to partial restore snapshot (i.e. only zerotier addon), so there is no need to use any other methods (of course system must be accesible).

**Comment by SamKr** [comment]
> I got 2 plans: 1 rollback to ZeroTier 1.4.6 (while maintaining the OS upgrades), and the other is a possible fix while maintaining the upgrade.
> 
> I consider the latter the wished-for situation, but currently exploring and testing that one.

I'd agree that the fix maintaining the upgrade would be preferable. And I'm fine with waiting so you can have enough time to build and test. Since @rapejim implemented a workaround for his critical system, I think the pressure's off for a bit? But of course I don't know if that's the case for everyone.

**Comment by sipodd** [comment]
The partial snapshot restore, which I totally forgot until @rapejim mentioned it(thx man!) , worked like a charm for me.
So no pressure,from my side, in fixing the issue with 0.8.0.

**Comment by mituhome** [comment]
I also had a similar situation when updating to version 0.8.0. I tried removing the addon over and over again but still can't connect.
`[23:45:39] INFO: Starting ZeroTier One...
[23:45:40] INFO: Starting ZeroTier One...
[23:45:41] INFO: Starting ZeroTier One...
[23:45:43] INFO: Starting ZeroTier One...
[23:45:45] INFO: Starting ZeroTier One...
[23:45:46] INFO: Starting ZeroTier One...
[23:45:47] INFO: Starting ZeroTier One...
[23:45:49] INFO: Starting ZeroTier One...
[23:45:50] INFO: Starting ZeroTier One...
[23:45:51] INFO: Starting ZeroTier One...
[23:45:53] INFO: Starting ZeroTier One...
[23:45:54] INFO: Starting ZeroTier One...
[23:45:56] INFO: Starting ZeroTier One...
[23:45:57] INFO: Starting ZeroTier One...
[23:45:58] INFO: Starting ZeroTier One...
[23:46:00] INFO: Starting ZeroTier One...
[23:46:01] INFO: Starting ZeroTier One...
[23:46:03] INFO: Starting ZeroTier One...
[23:46:05] INFO: Starting ZeroTier One...
[23:46:06] INFO: Starting ZeroTier One...
[23:46:07] INFO: Starting ZeroTier One...
[23:46:09] INFO: Starting ZeroTier One...`

Home Assistant's log shows Error:
`Error handling request
23:05:44 – /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py (ERROR)
Error sending through socket 17
10:45:37 – /usr/local/lib/python3.8/site-packages/zeroconf/__init__.py (WARNING)`

**Comment by frenck** [comment]
ZeroTier 0.9.0 is now available in the add-on store.
