### ISSUE TITLE
Accessing local network over ZeroTier add-on not possible.....

### ISSUE THREAD

**Issue by ralbright-wa** [hassio-addons/addon-zerotier#190]
# Problem/Motivation

> I have been utilizing ZeroTier in quite a few environments, and one thing I do on all of my anchoring points in a network (the device that I install in a client's network) is set up the networking on the device to allow me to access their network and its resources while connected via ZeroTier. I am putting this Add-on on my home assistant which is installed in my travel trailer. My travel trailer has a full time internet via Starlink (flat mounted on roof) and cellular backup. 

## Expected behavior

>I expected to be able to modify the networking parameters of my end point like it is described here: [https://zerotier.atlassian.net/wiki/spaces/SD/pages/224395274/Route+between+ZeroTier+and+Physical+Networks](https://zerotier.atlassian.net/wiki/spaces/SD/pages/224395274/Route+between+ZeroTier+and+Physical+Networks)

## Actual behavior

> At present, I cannot seem to find on the terminal where this ZeroTier install is interacting with the local device to make the noted changes for IP Forwarding to/from ZeroTier and remote client

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> The way I see it, this could be done relatively easy from the coding stand-point, as an optional switched item to allow local network access via ZeroTier.

**Comment by wired-dev** [comment]
Yeah it's seems to be of the last update or two when stuff changed

**Comment by ralbright-wa** [comment]
At present, I have removed the add-on for ZeroTier and added it like I would normally do so, this is still allowing me the access that I need. I would love to have this inside of home assistant, but will settle for where it is now.

**Comment by ralbright-wa** [comment]
So I have removed this add-on and have no plans to re-add it. As doing so breaks many things that I operate within ZeroTier infrastructure. Installing ZeroTier without this add-on allows full control of everything and it works very well. So I can not recommend this add-on for anyone.
