### ISSUE TITLE
Doesn't support secrets.yaml 

### ISSUE THREAD

**Issue by DavidFW1960** [hassio-addons/addon-zerotier#2]
# Problem/Motivation
Configured secrets but it does not accept
> (Why the issue was filed)

## Expected behavior
Should accept secrets
> (What you expected to happen)

## Actual behavior
![image](https://user-images.githubusercontent.com/36390762/55445832-d8e31a80-5608-11e9-92c1-203e23844c09.png)

> (What actually happened)
configure secrets
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
I am just not using !secret and it works
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Fixed in dev. Will be released soon.
