### ISSUE TITLE
Upgrading to current ZeroTier release

### ISSUE THREAD

**Issue by genebean** [hassio-addons/addon-zerotier#20]
There seems to be a set of newer features that require at least ZeroTier 1.6.0... are you game to update things? I'm happy to send a PR if you want to point me in the right direction.

**Comment by frenck** [comment]
That is not a bug report.

**Comment by genebean** [comment]
It’s not a bug, but rather a feature request and an offer of help. Is there some other place for such things?

**Comment by frenck** [comment]
See add-on readme.

**Comment by genebean** [comment]
The contribution doc says feature requests go here

**Comment by frenck** [comment]
still closing it, and stopping this discussion as well. I like to focus on things that matter. Thanks.
