### ISSUE TITLE
Example configuration not working

### ISSUE THREAD

**Issue by timotoots** [hassio-addons/addon-zerotier#204]
# Problem/Motivation

Trying to set up Zerotier network on a freshly installed add-on and got an error message.  Even with the example YAML or adding network by hand.

## Expected behavior

Network id should be saved.

## Actual behavior

Got error message:
``
Failed to save add-on configuration, does not match regular expression ^!secret [a-zA-Z0-9_\-]+$|[0-9a-z]{16}. Got {'networks': ['wgfyiwe73747457', 'fhu3888892jjfdk'], 'api_auth_token': ''}
``

## Steps to reproduce
Add add-on. Use example configuration.

## Proposed changes

Probably needs some fixing.

**Comment by tjorim** [comment]
Note: This is just an example, don't copy and paste it! Create your own!

**Comment by tjorim** [comment]
The examples are only 15 characters long, a real network ID would be 16.

**Comment by timotoots** [comment]
Thank you!
It was the incorrect network ID that I tried to use. Maybe adding better error message would make sense. Or validate before saving.

**Comment by tjorim** [comment]
The Supervisor handles that: "Failed to save add-on configuration" makes it pretty clear it did not save the config because it validated it.
