### ISSUE TITLE
mDNS / avahi / bonjour resolving of `homeassistant.local` does not work over zerotier

### ISSUE THREAD

**Issue by wucke13** [hassio-addons/addon-zerotier#211]
# Problem/Motivation

I want to access my homeassistant instance via `homeassistant.local`.

## Expected behavior

Any device from within the zerotier network that the HAOS VM is joined into can resolve `homeassistant.local`

## Actual behavior

My HAOS instance is accessed using the `homeassistant.local` domain, which is resolved via mDNS. This works fine from the local network connected to HAOS, i.e. via mDNS I can resolve `homeassistant.local`. However, from the zerotier network, I can not resolve `homeassistant.local` at all. Resolving other devices within the zerotier network using mDNS does work just fine.

## Steps to reproduce

1. Install HAOS
2. Add the zerotier add-on
3. Join a zerotier network
4. Resolve `homeassistant.local` from the local network of HAOS (should **work**)
5. Resolve `homeassistant.local` from the zerotier network (should **not work**)

## Proposed changes

Make sure that avahi (or whichever mDNS advertiser is used in HAOS) advertises as well in the zerotier network.

**Comment by domgregori** [comment]
I believe I run into the same issue when trying to use HomeKit Bridge over ZeroTier. It's not being broadcasted.
