### ISSUE TITLE
IPv4 forwarding to access local LAN

### ISSUE THREAD

**Issue by dec0dOS** [hassio-addons/addon-zerotier#23]
# Problem/Motivation

> I want to access my local LAN via ZeroTier, not only the Home Assistant OS host. It could be easily set up via managed routes and enabled ipv4 forwarding on Linux. I'm trying to figure out how to enable ipv4 forwarding on Home Assistant OS and/or ZeroTier extension.

## Expected behavior

> Creating a new managed route in ZeroTier Central creates access to local LAN.
## Actual behavior

> No access

## Steps to reproduce
> Install and set up ZeroTier extension. Join the network. Create a managed route that forwards the local LAN via ZeroTier address.

## Proposed changes

> Update documentation on how to enable ipv4 forwarding on Home Assistant OS and extension code if necessary.

**Comment by frenck** [comment]
The system is not designed to run that way. If you have questions about HassOS, I suggest getting support with that project itself.

I consider that out of scope for the add-on perspective.
