### ISSUE TITLE
No connection to ZeroTier

### ISSUE THREAD

**Issue by Ferdinand99** [hassio-addons/addon-zerotier#254]
# Problem/Motivation

> It won't connect to my ZeroTier network

## Expected behavior

> Connection to zerotier so i can make "Remote-Home assistant" work. Should also be able to connect to home assistant in my browser using the *ZeroTier ip*:8123, but I have no connection to it

## Actual behavior

> No connection to ZeroTier. Log says:

```
 Add-on version: 0.19.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (amd64 / qemux86-64)
 Home Assistant Core: 2024.12.3
 Home Assistant Supervisor: 2024.11.4

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-zerotier: starting
[21:05:20] INFO: ZeroTier node address: 9203a6d5e6
[21:05:20] INFO: Configuring network: e5cd7a9e1c00de94
s6-rc: info: service init-zerotier successfully started
s6-rc: info: service zerotier: starting
s6-rc: info: service zerotier successfully started
s6-rc: info: service legacy-services: starting
[21:05:20] INFO: Starting ZeroTier One...
Starting Control Plane...
Starting V6 Control Plane...
ERROR: unable to configure virtual network port: could not open TUN/TAP device: No such file or directory
s6-rc: info: service legacy-services successfully started
```

## Steps to reproduce

>  Core 2024.12.3
Supervisor 2024.11.4
Operating System
Frontend 20241127.8

**Comment by sinclairpaul** [comment]
> TUN/TAP device: No such file or directory

and

> System: Debian GNU/Linux 12 (bookworm)  (amd64 / qemux86-64)

Would point to missing configuration on your Operating System.

**Comment by Ferdinand99** [comment]
I don't understand what's missing. It worked for months and then stopped working suddenly. What configuration on my operating system would that be?

**Comment by frenck** [comment]
Hi there @Ferdinand99 👋 

You are running an advanced installation method: Home Assistant Supervised.

With this installation method, you bring your own operating system. The Home Assistant project assumes one using that method is familiar with advanced network and Linux administration concepts in order to manage those. Your latter question is a bit off with that concept (please, don't get me wrong, I don't mean it in a bad way saying this), you might want to consider if this is the right installation method for you.

That said, the error message indicates your kernel module that provides the TAP/TUN device drivers isn't loaded. Make sure they are part of your currently active kernel.

I'm going to close this issue on this end, as this is not an add-on issue.

../Frenck

**Comment by MostHated** [comment]
@Ferdinand99 

Did you get this figured out? I just ran into this myself after having did OS updates. I was about to start digging but figured it was worth a check first to see if someone found a simple solution?

**Comment by frenck** [comment]
Still... if these are questions.. you are really using the wrong platform and would highly recommend looking for something that better fit you.

Even if it runs now, soon you will hit an issue that will make you frustrated or start pulling your hair again.

Pick something you understand or can easier manage, so you can focus on the actual automating of your home.

../Frenck

**Comment by MostHated** [comment]
I appreciate your concern, but my home is and has been adequately automated for several years.  I am well aware of my own capabilities, what I do and do not understand, and what "fits me".

**Comment by frenck** [comment]
Considering this raised a question for you, is strongly disagree.

**Comment by MostHated** [comment]
Ok. :+1:
