### ISSUE TITLE
can not save network id

### ISSUE THREAD

**Issue by jj-x** [hassio-addons/addon-zerotier#4]
![Capture](https://user-images.githubusercontent.com/38894634/55450772-e7441e80-5595-11e9-8cff-fee1e0b7a678.PNG)
# Problem/Motivation
19-04-03 03:00:37 ERROR (SyncWorker_1) [hassio.docker] Can't start addon_a0d7b954_zerotier: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory")
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by ascillato** [comment]
This is duplicated from https://github.com/hassio-addons/addon-zerotier/issues/2
