### ISSUE TITLE
zero tier - iphone

### ISSUE THREAD

**Issue by gastonc** [hassio-addons/addon-zerotier#45]
# Problem/Motivation

home assistant + zero tier does not work on iphone phones

> (Why the issue was filed)

I installed the zero tier addon on my home assistant
- core version: 2021.3.3
- supervisor version: 2021.02.11
On my android phone it works perfect but on iphone phones it doesn't work. I tested with two browsers (safari and chrome) and it doesn't work
I also installed it on an apple tablet and it works fine
Someone can help me find the solution.
Thanks a lot

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The add-on provides connectivity from Home Assistant -> Zerotier. As you wrote, this works.

If you have problems connecting your iPhone to the ZeroTier One network, I think you should contact ZeroTier. This add-on had nothing to do with their apps.
