### ISSUE TITLE
Error message - not a valid value for dictionary value

### ISSUE THREAD

**Issue by cmlittle** [hassio-addons/addon-zerotier#5]
I created a free account and set the "Internal ID" in the "network ID" field of the add-on as well as the API token and when I press save I get the following error:

not a valid value for dictionary value @ data['options']. Got {'network_id': 'xxxxxxxxx', 'port': 9993, 'api_auth_token': 'xxxxxxxxx'}

Am I missing something here? Is the Network ID the same as the "Internal ID" on the ZeroTier account page?

**Comment by ascillato** [comment]
>Is the Network ID the same as the "Internal ID" on the ZeroTier account page

No,

You have to go to **network** in the ZeroTier page and find **Network ID**

This AddOn is working for me.

**Comment by cmlittle** [comment]
> You have to go to network in the ZeroTier page and find Network ID

Thank you and sorry for the stupid question. That worked for me.

**Comment by frenck** [comment]
Glad it is resolved @cmlittle! 🎉
