### ISSUE TITLE
ZeroTier loses connectivity forever after power cycling the Internet router (sometimes)

### ISSUE THREAD

**Issue by HardSoftMus** [hassio-addons/addon-zerotier#51]
# Problem/Motivation

>ZeroTier loses connectivity forever after power cycling the Internet router (sometimes)

## Expected behavior

> To remain connected after temporary Internet loses

## Actual behavior

> Sometimes I power off and on the Internet Router of the operator to get a new IP address.
Usually, after the router gets reconnected, ZeroTier gets reconnected without problem, but sometimes, although I have access to the page of Home Assistant, ZeroTier disconnects forever. It is necessary to power cycle the Raspberry Pi 4B to restore connection. The error shown in the log is "sendto: Network unreachable" that repeats forever.

## Steps to reproduce
Power off the Internet Router and power on again until Zerotier cannot longer reconnect.

> (How can someone else make/see it happen)
Don't know

## Proposed changes

Apart from solving this issue, It would be very interesting to have a Home Assistant variable that shows the connection state of ZeroTier.
It would be nice to see the connection status in the Dashboard, Isn't it?

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Thanks a lot for this wonderful plug-in

**Comment by frenck** [comment]
I'm sorry, but I cannot do anything with: Sometimes it doesn't work.

Please provide a reproduction that works all the time, or at least provide logs, from when the issue occurs, with error details.

> Apart from solving this issue, It would be very interesting to have a Home Assistant variable that shows the connection state of ZeroTier.

This is not the Home Assistant project.
