### ISSUE TITLE
Node ID not cleared by a reset of configuration or a reinstall of plugin

### ISSUE THREAD

**Issue by jfiger** [hassio-addons/addon-zerotier#58]
# Problem/Motivation

>cannot change Node ID  when needed for example when restoring a backup on another HA instance.

## Expected behavior

> According to the [Zerotier documentation](https://zerotier.atlassian.net/wiki/spaces/SD/pages/327693/How+to+Clear+Reset+your+ZeroTier+Address)
Delete the files identity.public and identity.secret from ZeroTier's working directory.".
On Linux this is usually "/var/lib/zerotier-one".

## Actual behavior

> The old Node ID is kept even if you reinstall the plugin or reset the configuration

## Steps to reproduce

> reinstall or reset the configuration and   look at the log

## Proposed changes

> delete node ID when reinstall or reset the configuration of the plugin or give the option to.

**Comment by frenck** [comment]
All keys/certificates for the Home Assistant platform are stored in: `/ssl`, in this case specifically: `/ssl/zerotier`.

**Comment by jfiger** [comment]
Thank you. Excellent !
