### ISSUE TITLE
Enable IP forwarding

### ISSUE THREAD

**Issue by StevusPrimus** [hassio-addons/addon-zerotier#7]
# Problem/Motivation

It would be absolutely nice, if IP Forwarding could be enabled, that the addon can be used as VPN Endpoint

## Expected behavior

Ip Forwarding being enabled. Perfect would be a switch to enable/disable IP forwarding for IPv4/IPv6

## Actual behavior

IP Forwarding is not enabled in the docker container

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Ip Forwarding being enabled. Perfect would be a switch to enable/disable IP forwarding for IPv4/IPv6

**Comment by frenck** [comment]
Hi @StevusPrimus,

Thank you for your suggestion. I'm not sure how to achieve that within the scope of Hass.io. Do you have a suggestion on how to do that?

../Frenck

**Comment by frenck** [comment]
No response from issue author in 12 days. Closing.
