### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by miraixyz** [hassio-addons/addon-zerotier#8]
# Problem/Motivation

>No device can access my Pi through ZeroTier

## Expected behavior

> To be ble to ping, and access my Home Assistant Pi through browser using the IP address provided by ZeroTier. http://xxx.xxx.xxx.xxx:8123 

## Actual behavior

> Other devices on the ZeroTier VPN can access and ping each other, but cannot access HA.  The ZeroTier management page shows it as being connected and reflects the correct network ID and MAC address of the Pi, but nothing can access it.  I can't ping to/from the Pi

## Steps to reproduce

> not sure

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Is anyone having this issue except me?

**Comment by StevusPrimus** [comment]
Hi, can you paste a screenshot of https://my.zerotier.com/network/XXXYOURNETWORKID the members section? You might grey out sensible data.

**Comment by miraixyz** [comment]
Thanks for looking into this.  Here are the screenshots that you asked for:

Looks as if everything is configured  and connected tot he same network, but nothing can connect to HA.  If I put two iphones on ZeroTier, they can ping to each other despite being on different carriers, but nothing can connect to HA.
![zerot](https://user-images.githubusercontent.com/36748647/56278344-01a6fc00-6141-11e9-8d50-aa6b8947b2af.jpg)

![zerotadd](https://user-images.githubusercontent.com/36748647/56278398-1e433400-6141-11e9-8d07-c45b0041068f.jpg)

**Comment by zguithues** [comment]
fresh install today and it worked as expected.  i know this isn't super helpful, but i just wanted to throw out that it's not completely broken.

i'm using a pi3 with hassio
my log looks the same as yours.
your zerotier looks just as i would expect it to.

you might try giving the ha device an different ip address and see if that helps.
you might also try increasing the log level
is "protection mode" enabled at the top of the plugin page?

just a few shots in the dark.  hopefully you can get it worked out.  good luck :)

**Comment by miraixyz** [comment]
Thanks for the suggestion.  I managed to resolve this problem.  Seems that there was an issue with the virtual network that I had created on the zerotier site, so I blew it away and created a new one, and now it works.

**Comment by frenck** [comment]
Nice!
