### ISSUE TITLE
Unable to save network id

### ISSUE THREAD

**Issue by yousaf465** [hassio-addons/addon-zerotier#81]
# Problem/Motivation

> I am unable to save my network id in zero-tier add-on configuration tab. 

## Expected behavior

> it should save my network id in configuration. 
## Actual behavior

> restores to default `networks: []
api_auth_token: ''`

## Steps to reproduce

> replace [] with network id and click save. 

## Proposed changes

> anything to fix this behaviour.

**Comment by sinclairpaul** [comment]
Please see the example in the documentation at https://github.com/hassio-addons/addon-zerotier/blob/main/zerotier/DOCS.md#configuration

It is an array, so the ```-``` is important

**Comment by frenck** [comment]
Please provide a reproduction, e.g., by providing example data that is problematic.

Without it, there is nothing we can or will do.

**Comment by yousaf465** [comment]
> Please provide a reproduction, e.g., by providing example data that is problematic.
> 
> Without it, there is nothing we can or will do.

Thanks for the reply. But the issue was resolved. I just copied the code `networks:
  - wgfyiwe73747457
  - fhu3888892jjfdk
api_auth_token: ""'
and replace the first network id with my own and removed the second one. Solution here https://community.home-assistant.io/t/home-assistant-community-add-on-zerotier-one/109091/118?u=yousaf465

**Comment by frenck** [comment]
That is not a solution, I think you need to read up into how YAML works...

Closing the issue, as it is not an issue.
