### ISSUE TITLE
I am useing NAT Carrier 4G , Let's Encrypt SSL possible  with ZeroTier?

### ISSUE THREAD

**Issue by xkinghost** [hassio-addons/addon-zerotier#9]
I use Zero Tier One addon. Zero tier provide me an ip address to connect Hassio UI.
I register an ClouDNS: Free DNS  and domain names. And point domain to this ip
My domain is http://www.kibihome.cloudns.asia:8123
How can i make Let's Encrypt SSL or another ssl for this throught setting in Zero Tier One and my hassio

**Comment by frenck** [comment]
It is a VPN.... Let's encrypt does not apply here...
